# Generated by Django 5.2.3 on 2025-07-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="mobile",
            field=models.CharField(default="9999999999", max_length=15),
        ),
    ]
